### PR TITLE
Add a CODEOWNERS file

### PR DESCRIPTION
**Pull request by alexef**
Add a CODEOWNERS file based on either the existing _gygservice.yml_ file or the top committers to this repo.
Note that a codeowners file is important to ensure automated PRs are assigned to the correct team.

### CODE REVIEW

**Comment by trodrigues** [comment]
I'm not sure this should be assigned to specific product teams like Activity Content but probably to the current Pool Owner (@eleonoraborghi) and whoever else currently supervises the recruitment process for the Full Stack roles.

**Comment by andrespring** [comment]
> I'm not sure this should be assigned to specific product teams like Activity Content but probably to the current Pool Owner (@eleonoraborghi) and whoever else currently supervises the recruitment process for the Full Stack roles.

Yes. I agree this should be the pool owner for the full stack roles. This currently is @eleonoraborghi .

**Comment by alexef** [comment]
I'll create a virtual team with one member (@eleonoraborghi ) and assign that team to it. Thank you all for clarity.

**Comment by alexef** [comment]
https://github.com/getyourguide/organisation/pull/943

**Review by andrespring — APPROVED** [review]

**Pull request merged**
